## DataFrames

In Julia dataframes are handled by an addon package. It can be installed with:

```{julia; eval=false}
Pkg.add("DataFrames")
```

it's very likely that you will want to read and write dataframes as CSV files at some stage. This functionality is provided by the `CSV.jl` package, so you should install it as well:

```{julia; eval=false}
Pkg.add("CSV")
```

to use the `DataFrames` and `CSV` packages you need to load them:

```{julia}
using CSV, DataFrames
```

let's create a numeric vector and a string vector of the same length, and then put them in a dataframe:

```{julia}
y = rand(10)
cnd = [["a" for i=1:5]; ["b" for i=1:5]]
resFrame =  DataFrame(y=y, cnd=cnd)
```

to access the columns of a dataframe use the following syntax:

```{julia}
resFrame[:y] #retrieves the column named `y`
resFrame[:cnd] #retrieves the column named `cnd`
```

note that `:y` or `:cnd` are *Symbols*:

```{julia}
typeof(:y)
```

sometimes it is necessary to access the column of a dataframe using a string. You can do so by converting a string to a symbol:

```{julia}
resFrame[Symbol("y")]
```

you can also retrieve a column by its column number

```{julia}
resFrame[1]
```

to write a dataframe to a text of CSV file, use:

```{julia}
CSV.write("dataframe.csv", resFrame)
```

it is also possible to specify a separator, note that the separator character must be enclosed by
single ticks `''`:

```{julia}
CSV.write("dataframe.csv", resFrame, delim=';')
```

Selecting:

```{julia; eval=false}
ds[(ds[:montage] .== "FzIpsiMast") & (ds[:ear] .== "both"), :]
```
